nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

hostAliases:

resources: {}

fullhouse:
  image:
    name: philmtd/full-house
    tag: ""
    imagePullPolicy: IfNotPresent

serviceMonitor:
  enabled: false
  interval: 10s

startupProbe:
  failureThreshold: 10
  initialDelaySeconds: 0
  timeoutSeconds: 1
  periodSeconds: 2

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 0
  timeoutSeconds: 5
  periodSeconds: 1

livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 0
  timeoutSeconds: 5
  periodSeconds: 10

service:
  annotations: {}
  type:
  sessionAffinity: None
  sessionAffinityConfig: {}
  loadBalancerIP:
  clusterIP:

ingress:
  defaultBackend:
    enabled: false
  hosts:
  tls:
  annotations: {}
