## @section Common parameters
##

## @param nameOverride String to partially override the name
nameOverride: ""

## @param fullnameOverride String to fully override the release name
fullnameOverride: ""

## @param imagePullSecrets Docker registry secret names as an array
imagePullSecrets: []

## @param hostAliases Host aliases available to the application
hostAliases:

## @param resources.limits The resource limits for the container
## @param resources.requests The resource requests for the container
resources:
  limits: {}
  requests: {}

## @section Full House parameters
## Parameters which configure the Full House installation
##

fullhouse:

  ## @param fullhouse.image.name The container image repository
  ## @param fullhouse.image.tag The container image tag, defaults to `Chart.AppVersion` if not set
  ## @param fullhouse.image.imagePullPolicy Image Pull Policy
  image:
    name: philmtd/full-house
    tag: ""
    imagePullPolicy: IfNotPresent

  ## @param fullhouse.configuration The Full House configuration file contents as yaml. Not required and will be merged with the default configuration.
  configuration:

## @section Probes
##

## @param startupProbe.failureThreshold Failure threshold for startupProbe
## @param startupProbe.initialDelaySeconds Initial delay seconds for startupProbe
## @param startupProbe.timeoutSeconds Timeout seconds for startupProbe
## @param startupProbe.periodSeconds Period seconds for startupProbe
startupProbe:
  failureThreshold: 10
  initialDelaySeconds: 0
  timeoutSeconds: 1
  periodSeconds: 2

## @param readinessProbe.failureThreshold Failure threshold for readinessProbe
## @param readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
## @param readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
## @param readinessProbe.periodSeconds Period seconds for readinessProbe
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 0
  timeoutSeconds: 5
  periodSeconds: 1

## @param livenessProbe.failureThreshold Failure threshold for livenessProbe
## @param livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
## @param livenessProbe.timeoutSeconds Timeout seconds for livenessProbe
## @param livenessProbe.periodSeconds Period seconds for livenessProbe
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 0
  timeoutSeconds: 5
  periodSeconds: 10

## @section Traffic Exposure parameters
##

service:
  ## @param service.annotations annotations for the service
  annotations: {}
  ## @param service.type Kubernetes service type
  type:
  ## @param service.sessionAffinity the service's sessionAffinity
  sessionAffinity: None
  ## @param service.sessionAffinityConfig additional sessionAffinity configuration
  sessionAffinityConfig: {}
  ## @param service.loadBalancerIP A loadBalancerIP configuration
  loadBalancerIP:
  ## @param service.clusterIP The service's clusterIP
  clusterIP:

ingress:
  ## @param ingress.ingressClassName name of the ingressClass used for the ingress
  ingressClassName:
  ## @param ingress.hosts Array with hostnames used for the ingress
  ## e.g.
  ## hosts:
  ##   - host: "fullhouse.my-company.com"
  hosts:
  ## @param ingress.tls TLS configuration of the ingress as an array
  ## e.g.
  ## tls:
  ##   - hosts:
  ##     - "fullhouse.my-company.com"
  ##     secretName: fullhouse-tls
  tls:
  ## @param ingress.annotations annotations for the ingress
  annotations: {}

## @section Metrics
##
## Specific for the use with the kube-prometheus-stack

## @param serviceMonitor.enabled Whether the serviceMonitor resource should be deployed
## @param serviceMonitor.interval Prometheus scrape interval
serviceMonitor:
  enabled: false
  interval: 10s
