apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{- include "full-house.labels" . | nindent 4 }}
  name: {{ include "full-house.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "full-house.selectorLabels" . | nindent 6 }}
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 10
  template:
    metadata:
      labels: {{- include "full-house.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: full-house
          image: {{ (printf "%s:%s" .Values.fullhouse.image.name (.Values.fullhouse.image.tag | default .Chart.AppVersion)) | quote }}
          imagePullPolicy: {{ .Values.fullhouse.image.imagePullPolicy }}
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8090
              name: metrics
          {{- with .Values.livenessProbe }}
          volumeMounts:
            - mountPath: /app/config/fullhouse.yaml
              name: config
              subPath: fullhouse.yaml
              readOnly: true
          livenessProbe:
            httpGet:
              path: /up
              port: http
            failureThreshold: {{ .failureThreshold }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            httpGet:
              path: /up
              port: http
            failureThreshold: {{ .failureThreshold }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            httpGet:
              path: /up
              port: http
            failureThreshold: {{ .failureThreshold }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
          {{- end }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: {{ include "full-house.fullname" . }}
            optional: true
